export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const REGISTER = "REGISTER";

/* PRODUCTS ACTION TYPES */
export const GET_PRODUCTS_BY_ARRIVAL = "GET_PRODUCTS_BY_ARRIVAL";
export const GET_PRODUCTS_BY_SELL = "GET_PRODUCTS_BY_SELL";
export const GET_BRANDS = "GET_BRANDS";
export const GET_WOODS = "GET_WOODS";
